<a href="https://colab.research.google.com/github/Aldo380/loominizing/blob/main/RelearningPytorchAgain.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.6.0+cu124'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar2 = torch.tensor(9)
scalar2

tensor(9)

In [4]:
scalar.ndim

0

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape #Shape tells us how elements are arrange inside.

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX2 = torch.tensor([[23, 24],
                        [25, 26],
                        [27, 28]])
MATRIX2

tensor([[23, 24],
        [25, 26],
        [27, 28]])

In [11]:
MATRIX2.shape #sHAPE GIVES THE ORDER OF NMATIX
MATRIX2.ndim

2

In [12]:
 ##mMulti dimmensional array of numbers

# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

##rANDOM TENSRORS

In [15]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3799, 0.1339, 0.2912, 0.9283],
         [0.0104, 0.1403, 0.5356, 0.6200],
         [0.1400, 0.1550, 0.8278, 0.6023]]),
 torch.float32)

In [17]:
randtensor2 = torch.rand(size=(3, 4))
randtensor2.shape, randtensor2

(torch.Size([3, 4]),
 tensor([[0.0521, 0.4807, 0.3748, 0.7405],
         [0.9532, 0.7159, 0.2427, 0.9811],
         [0.3447, 0.4640, 0.9305, 0.0038]]))

In [19]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3)) #224 pixel width, 224 pixels height, 3 value of color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [21]:
zeros2 = torch.zeros(size=(4,4))

zeros2, zeros2.dtype, zeros2.shape , zeros2.ndim

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32,
 torch.Size([4, 4]),
 2)

In [22]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [24]:
ones2 = torch.ones(size=(4,4))
ones2, ones2.dtype, ones2.shape, ones2.ndim# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [25]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))